export default class CommonConstants{
  // 表示全长
  static readonly FULL_LENGTH:string = '100%'

  // 标题宽度
  static readonly TITLE_WIDTH:string = '80%'

  // 列表默认宽度
  static readonly LIST_DEFAULT_WIDTH:string = '93.3%'

  // 默认透明度
  static readonly OPACITY_DEFAULT:number = 1

  // 完成时透明度
  static readonly OPACITY_COMPLETED:number = 0.4

  // 圆角半径
  static readonly BORDER_RADIUS:number = 24

  // 字体粗细
  static readonly FONT_WEIGHT:number=500

  // 列间距
  static readonly COLUMN_SPACE:number = 16
}