export default class CommonConstants {
  static readonly app_color = '#147D42'
  static readonly FULL_WIDTH = '100%';
  static readonly FULL_HEIGHT = '100%';
  static readonly DIALOG_HEIGHT = '95%';
  static readonly TABS_HEIGHT = '70%';
  static readonly MINIMUM_SIZE = 0;
  static readonly FULL_SIZE = 1;
  static readonly PROMPT_BOTTOM = '70vp';
  static readonly EDIT_POSITION_X = '43.5%';
  static readonly EDIT_POSITION_Y = '90%';
}